"""describe your change

Revision ID: 040e037ec4a8
Revises: a1889f7766d6
Create Date: 2025-07-19 16:12:31.998940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040e037ec4a8'
down_revision: Union[str, Sequence[str], None] = 'a1889f7766d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('vehicle_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.add_column('vehicles', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'drivers', ['driver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    op.drop_column('vehicles', 'driver_id')
    op.alter_column('vehicle_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
