"""describe your change

Revision ID: 1019adeb8b3b
Revises: 3f0b06b23cbb
Create Date: 2025-07-19 05:27:45.630068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1019adeb8b3b'
down_revision: Union[str, Sequence[str], None] = '3f0b06b23cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('vehicle_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.add_column('vehicles', sa.Column('vehicle_config_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vehicles', 'vehicle_config', ['vehicle_config_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'vehicle_config_id')
    op.alter_column('vehicle_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
