"""describe your change

Revision ID: 27df2e5976c6
Revises: 670a22a259e1
Create Date: 2025-07-13 22:11:08.624584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27df2e5976c6'
down_revision: Union[str, Sequence[str], None] = '670a22a259e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_status', sa.String(), nullable=False))
    op.drop_column('bookings', 'booking_Status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_Status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'booking_status')
    # ### end Alembic commands ###
