"""describe your change

Revision ID: 53069ad5891b
Revises: 9f97e7aa1847
Create Date: 2025-07-14 00:02:12.904918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53069ad5891b'
down_revision: Union[str, Sequence[str], None] = '9f97e7aa1847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('rider_id', sa.UUID(), nullable=False))
    op.alter_column('bookings', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('bookings_tenant_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['rider_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_tenant_id_fkey'), 'bookings', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('bookings', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('bookings', 'rider_id')
    # ### end Alembic commands ###
