"""describe your change

Revision ID: 557619dd901f
Revises: ec00d74d2bdc
Create Date: 2025-08-06 18:38:12.139742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557619dd901f'
down_revision: Union[str, Sequence[str], None] = 'ec00d74d2bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('total_ride_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('tenants', sa.Column('stripe_cutomer_id', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('stripe_account_id', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_plan', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('daily_ride_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('tenants', sa.Column('last_ride_count_reset', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.create_index(op.f('ix_tenants_stripe_account_id'), 'tenants', ['stripe_account_id'], unique=False)
    op.create_index(op.f('ix_tenants_stripe_cutomer_id'), 'tenants', ['stripe_cutomer_id'], unique=False)
    op.drop_column('tenants', 'plan')
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('vehicle_category_rate', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('vehicle_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('vehicle_category_rate', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.add_column('tenants', sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tenants_stripe_cutomer_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_stripe_account_id'), table_name='tenants')
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.drop_column('tenants', 'last_ride_count_reset')
    op.drop_column('tenants', 'daily_ride_count')
    op.drop_column('tenants', 'subscription_plan')
    op.drop_column('tenants', 'subscription_status')
    op.drop_column('tenants', 'stripe_account_id')
    op.drop_column('tenants', 'stripe_cutomer_id')
    op.drop_column('tenants', 'total_ride_count')
    # ### end Alembic commands ###
