"""describe your change

Revision ID: 670a22a259e1
Revises: 
Create Date: 2025-07-13 21:36:46.224229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670a22a259e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('service_type', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('pickup_location', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('dropoff_location', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('city', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('booking_Status', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('pricing', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('notes', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'bookings', ['id'])
    op.create_foreign_key(None, 'bookings', 'drivers', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'drivers', ['driver_id'], ['id'])
    op.create_unique_constraint(None, 'drivers', ['id'])
    op.create_unique_constraint(None, 'tenants', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'vehicles', ['id'])
    op.create_foreign_key(None, 'vehicles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='unique')
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'pricing')
    op.drop_column('bookings', 'booking_Status')
    op.drop_column('bookings', 'city')
    op.drop_column('bookings', 'dropoff_location')
    op.drop_column('bookings', 'pickup_location')
    op.drop_column('bookings', 'service_type')
    op.drop_column('bookings', 'vehicle_id')
    op.drop_column('bookings', 'tenant_id')
    op.drop_column('bookings', 'driver_id')
    # ### end Alembic commands ###
