"""describe your change

Revision ID: 8035b15aa511
Revises: 22bc5399539b
Create Date: 2025-07-19 20:26:36.749914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8035b15aa511'
down_revision: Union[str, Sequence[str], None] = '22bc5399539b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('vehicle_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.add_column('vehicles', sa.Column('make', sa.String(length=200), nullable=False))
    op.add_column('vehicles', sa.Column('model', sa.String(length=200), nullable=False))
    op.add_column('vehicles', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('vehicles', 'vehicle_make')
    op.drop_column('vehicles', 'vehicle_name')
    op.drop_column('vehicles', 'vehicle_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('vehicle_make', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('vehicles', 'year')
    op.drop_column('vehicles', 'model')
    op.drop_column('vehicles', 'make')
    op.alter_column('vehicle_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
