"""describe your change

Revision ID: 9f97e7aa1847
Revises: 27df2e5976c6
Create Date: 2025-07-13 22:16:00.634985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f97e7aa1847'
down_revision: Union[str, Sequence[str], None] = '27df2e5976c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_tenant_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_tenant_id_fkey'), 'bookings', 'drivers', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
