"""describe your change

Revision ID: d2218724ece1
Revises: d470373f060c
Create Date: 2025-07-18 22:34:26.430799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2218724ece1'
down_revision: Union[str, Sequence[str], None] = 'd470373f060c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
