"""describe your change

Revision ID: e9b41ce21389
Revises: 557619dd901f
Create Date: 2025-08-06 18:53:56.279214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b41ce21389'
down_revision: Union[str, Sequence[str], None] = '557619dd901f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('bookings', sa.Column('platform_fee_amount', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.String(), server_default='pending', nullable=True))
    op.add_column('drivers', sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    op.add_column('drivers', sa.Column('background_check_status', sa.String(length=50), nullable=True))
    op.add_column('drivers', sa.Column('stripe_onboaring_complete', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_drivers_stripe_account_id'), 'drivers', ['stripe_account_id'], unique=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('tenants', 'total_ride_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('vehicle_category_rate', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    op.alter_column('vehicle_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq')"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('vehicle_category_rate', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('tenants_settings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('tenants', 'total_ride_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('tenants', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('id_seq'::regclass)"),
               existing_nullable=False)
    op.drop_index(op.f('ix_drivers_stripe_account_id'), table_name='drivers')
    op.drop_column('drivers', 'stripe_onboaring_complete')
    op.drop_column('drivers', 'background_check_status')
    op.drop_column('drivers', 'stripe_account_id')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'platform_fee_amount')
    op.drop_column('bookings', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
